version: '3.8'
services:
    # vllm-model:
    #     build: ./vllm-model
    #     container_name: vllm-model
    #     ports:
    #         - "8000:8000"
    #     deploy:
    #         resources:
    #             reservations:
    #             devices:
    #                 - driver: nvidia
    #                   count: all
    #                   capabilities: [ gpu ]
    #     volumes:
    #         - ./vllm-model/huggingface:/root/.cache/huggingface

    backend:
        build: ./back-end/fast-api
        container_name: backend
        ports:
            - "8000:8000"
        volumes:
            - ./back-end/fast-api:/code
        env_file:
            - ./back-end/fast-api/.env

    frontend:
        build:
            context: ./front-end/local
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        container_name: frontend
        ports:
            - "3000:3000"
        env_file:
            - ./front-end/local/.env
